### ISSUE TITLE
Problem while compiling project

### ISSUE THREAD

**Issue by fcastel** [ibm-et/spark-kernel#145] opened 2015-10-01 08:19 UTC
Compilation of the project with sbt get stuck :

root@fea7b3fa27b5:/kernels/spark150# sbt --version
sbt launcher version 0.13.7
root@fea7b3fa27b5:/kernels/spark150# ls
client  communication  Dockerfile  kernel  kernel-api  LICENSE  macros  Makefile  NOTICE  project  protocol  README.md  resources  src  Vagrantfile
root@fea7b3fa27b5:/kernels/spark150# sbt --debug compile
[debug] > boot
[debug] > reload
[debug] > sbtStashOnFailure
[debug] > onFailure load-failed
[debug] > loadp
[debug] [Loading] Scanning directory /kernels/spark150/project
[debug] [Loading] Found non-root projects 
[debug] [Loading] Done in /kernels/spark150/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin)
[debug] sorting: ns: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin) not found List(sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin) not found List(sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin) not found List(sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin) not found List()
[debug]   :: sorted deduced result: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug] [Loading] Done in /kernels/spark150/project, returning: (spark150-build)
[info] Loading project definition from /kernels/spark150/project
[debug] Running task... Cancel: sbt.TaskCancellationStrategy$Null$@2aa7399c, check cycles: false

Same behavior is observed with 1.4.0 release but it seems ok with 1.3.1 on the same environment.

**Comment by lbustelo** [comment] 2015-10-01 11:46
Not saying that there is no problems, but I was working on master yesterday and build several times. It was slow, but completed. 
Gino B.

**Comment by fcastel** [comment] 2015-10-01 15:00
Thanks for the feedback, but it stayed stuck for hours.

Compilation was completed on another environment, but I can't tell what are the env differences that could explain that.

**Comment by lbustelo** [comment] 2015-11-06 17:30
Closing this since we can't reproduce.

**Closed by lbustelo** 2015-11-06 17:30 UTC
