### ISSUE TITLE
CodeCompleteHandler test failure

### ISSUE THREAD

**Issue by rcsenkbeil** [ibm-et/spark-kernel#39] opened 2015-01-17 09:03 UTC
Just encountered this error once while building. It isn't consistent, but it definitely failed once in the past five or six test runs.

![screen shot 2015-01-17 at 2 54 17 am](https://cloud.githubusercontent.com/assets/2481802/5788343/40444a80-9df5-11e4-9f10-2d78ffaac942.png)

@zackmorris, do you know what might be causing this?

**Comment by zackmorris** [comment] 2015-01-19 20:19
The error is caused by this line:
```
 // Set to 500ms because of a timing issue with the test
kernelMessageRelayProbe.receiveWhile(500.milliseconds)
```

After some discussion with @rcsenkbeil, I updated the unit tests in [CodeCompleteHandlerSpec](https://github.com/ibm-et/spark-kernel/blob/870a652c1fe094fba2aa9ed83e684bd8562b83cc/kernel/src/test/scala/com/ibm/spark/kernel/protocol/v5/handler/CodeCompleteHandlerSpec.scala) to use ```fishForMessage``` instead of ```receiveWhile```. This change should fix the root cause of the error: the test was timing out without receiving any messages. ```fishForMessage``` also allows us to check the content of the received message rather than reassigning that value to a temporary ```var``` and checking its content, which is what we were previously doing.

**Closed** 2015-01-19 20:22 UTC
Labels: bug
